/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileInsertionSort_InsertionSort */

#ifndef _Included_FileInsertionSort_InsertionSort
#define _Included_FileInsertionSort_InsertionSort
#ifdef __cplusplus
extern "C" {
#endif
#undef FileInsertionSort_InsertionSort_MIN_PRIORITY
#define FileInsertionSort_InsertionSort_MIN_PRIORITY 1L
#undef FileInsertionSort_InsertionSort_NORM_PRIORITY
#define FileInsertionSort_InsertionSort_NORM_PRIORITY 5L
#undef FileInsertionSort_InsertionSort_MAX_PRIORITY
#define FileInsertionSort_InsertionSort_MAX_PRIORITY 10L
/*
 * Class:     FileInsertionSort_InsertionSort
 * Method:    sort
 * Signature: (Ljava/lang/String;D)[I
 */
JNIEXPORT jintArray JNICALL Java_FileInsertionSort_00024InsertionSort_sort
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
